#!/usr/bin/perl
use strict;
use warnings;

my $url = 'git@github.com:teleshoes/klomp.git';
my $dir = 'klomp';
my $installCmd = './install-dependencies.pl; ./install.pl';

system "rm -rf /tmp/$dir";

system "git clone $url /tmp/$dir";

system "cd /tmp/$dir; $installCmd";
