#!/usr/bin/perl
use strict;
use warnings;

my $url = 'git://github.com/teleshoes/tpbattstat-applet.git';
my $dir = 'leds-tpbattstat-applet';
my $installCmd = 'cd led-controls; ./install-led-controls.sh';

system "rm -rf /tmp/$dir";

system "git clone $url /tmp/$dir";

system "cd /tmp/$dir; $installCmd";
