#!/bin/bash
sudo apt-get build-dep lightspark
sudo apt-get install libavformat-dev
sudo rm -rf /tmp/lightspark
git clone git://github.com/lightspark/lightspark.git /tmp/lightspark
cd /tmp/lightspark
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCOMPILE_PLUGIN=1 -DCMAKE_INSTALL_PREFIX=/usr ..
make
sudo make install
