#!/usr/bin/perl
use strict;
use warnings;

my $url = 'git://github.com/teleshoes/net.git';
my $dir = 'net';
my $installCmd = 'sudo ./install.pl';

system "rm -rf /tmp/$dir";

system "git clone $url /tmp/$dir";

system "cd /tmp/$dir; $installCmd";
