#!/bin/bash

echo "config file is ~/.notify-osd"
echo add options there, e.g.: "bubble-close-on-click = 1"

sudo apt-get remove notification-daemon
sudo add-apt-repository ppa:leolik/leolik
sudo apt-get update
sudo apt-get install notify-osd
