#!/usr/bin/perl
use strict;
use warnings;

my $srcConfig = "$ENV{HOME}/.picard";
my $destConfigDir = "$ENV{HOME}/.config/MusicBrainz";
my $destConfig = "$destConfigDir/Picard.conf";

sub run(@){
  print "@_\n";
  system "@_\n";
}

my @pkgs = qw(picard libchromaprint-tools);
run "sudo", "apt-get", "install", @pkgs;

my $now = time;
system "mkdir", "-p", $destConfigDir;
run "mv", $destConfig, "$destConfig-bak-$now";
run "cp", $srcConfig, $destConfig;
