#!/bin/bash
SS_DIR=/usr/share/fonts/truetype/ttf-silkscreen
sudo mkdir -p $SS_DIR
cd $SS_DIR
sudo wget http://www.kottke.org/plus/type/silkscreen/download/silkscreen.zip
sudo unzip silkscreen.zip
sudo rm silkscreen.zip
sudo fc-cache -fv
