#!/usr/bin/perl
use strict;
use warnings;

my $url = 'git://github.com/teleshoes/taffybar.git';
my $dir = 'taffybar';
my $installCmd = 'cabal install taffybar.cabal';

system "rm -rf /tmp/$dir";

system "git clone $url /tmp/$dir";

system "cd /tmp/$dir; $installCmd";
