#!/usr/bin/perl
use strict;
use warnings;

if(`whoami` ne "root\n"){
  print "rerunning as root\n";
  exec "sudo", $0, @ARGV;
}

sub run(@);
sub writeF($$);
sub readLines($);

my $w520_patch = '
462a463
> 		TP_DMI_MATCH("LENOVO", "ThinkPad"),
';

sub main(@){

  run "apt-get install tp-smapi-source";

  writeF "/etc/modprobe.d/tp_smapi.conf", "options thinkpad_ec force_io=1\n";
  run "modprobe -a tp_smapi";

  my $patchFile = "/tmp/tp_smapi-w520.patch";
  writeF $patchFile, $w520_patch;

  run "patch /usr/src/tp-smapi-0.40/thinkpad_ec.c $patchFile";

  run "module-assistant prepare tp-smapi";
  die "failed to install tp-smapi\n" if $? != 0;
  run "module-assistant auto-install tp-smapi -f";
  die "failed to install tp-smapi\n" if $? != 0;
  run "modprobe tp-smapi";

  my @lines = readLines "/etc/modules";
  my @newlines;
  for my $line(@lines){
    push @newlines, $line if $line !~ /^(tp-smapi)\n?$/;
  }
  push @newlines, "tp-smapi\n";

  writeF "/etc/modules", join '', @newlines;

  run "chmod o+w /etc/modules";
  run
    "echo 'KERNEL==\"event[0-9]*\", " .
    "ATTRS{phys}==\"hdaps/input1\"," .
    "ATTRS{modalias}==\"input:b0019v1014p5054e4801-*\",".
    "SYMLINK+=\"input/hdaps/accelerometer-event\"'".
    " | sudo tee /etc/udev/rules.d/51-hdaps.rules";
  run "update-initramfs -u";
}

sub run(@){
  print "@_\n";
  system @_;
}
sub writeF($$){
  my ($file, $content) = @_;
  open FH, "> $file";
  print FH $content;
  close FH;
}
sub readLines($){
  my ($file) = @_;
  open FH, '< /etc/modules';
  my @lines = <FH>;
  close FH;
  return @lines;
}

&main(@ARGV);
