#!/usr/bin/perl
use strict;
use warnings;

if(`whoami` ne "root\n"){
  print "rerunning as root\n";
  exec "sudo", $0, @ARGV;
}

sub run(@){
  print "@_\n";
  system @_;
}


run "apt-get install tp-smapi-source";

run
  "echo 'options thinkpad_ec force_io=1' > " .
  "/etc/modprobe.d/tp_smapi.conf";
run "modprobe -a tp_smapi";

my $w520_patch = '
462a463
> 		TP_DMI_MATCH("LENOVO", "ThinkPad"),
';

open FH, "> /tmp/tp_smapi-w520.patch";
print FH $w520_patch;
close FH;

run "patch /usr/src/tp-smapi-0.40/thinkpad_ec.c /tmp/tp_smapi-w520.patch";


run "module-assistant prepare tp-smapi";
run "module-assistant auto-install tp-smapi -f";
run "modprobe tp-smapi";

open FH, '< /etc/modules';
my @lines = <FH>;
close FH;
my @newlines;
for my $line(@lines){
  push @newlines, $line if $line !~ /^(tp-smapi)\n?$/;
}
push @newlines, "tp-smapi\n";

open FH, '> /etc/modules';
print FH @newlines;
close FH;

run "chmod o+w /etc/modules";
run
  "echo 'KERNEL==\"event[0-9]*\", " .
  "ATTRS{phys}==\"hdaps/input1\"," .
  "ATTRS{modalias}==\"input:b0019v1014p5054e4801-*\",".
  "SYMLINK+=\"input/hdaps/accelerometer-event\"'".
  " | sudo tee /etc/udev/rules.d/51-hdaps.rules";
run "update-initramfs -u";

