#!/usr/bin/perl
use strict;
use warnings;

my $confFile = "$ENV{HOME}/.config/tpbattstat.conf";

my @confLines = (
  "delay = 1000",
  "interface = SMAPI",
  "dischargeStrategy = SYSTEM",
  "dischargeLeapfrogThreshold = 5",
  "",
  "chargeStrategy = SYSTEM",
  "chargeLeapfrogThreshold = 10",
  "chargeBracketsPrefBattery = 1",
  "chargeBrackets = [10,20,80,90,95,100]",
  "",
  "displayPowerUsage = now",
  "displayColoredText = true",
  "displayIcons = true",
  "displayOnlyOneIcon = true",
  "displayBlinkingIndicator = true",
  "",
  "ledPatternsCharging = [blink-orange,blink-both,blink-green]",
  "ledPatternsDischarging = ["
    . "fastblink-orange,orange,orange,"
    . "both,both,both,"
    . "green,green,green,green"
  . "]",
  "ledPatternsIdle = [slowblink-green]",
);
@confLines = map {"$_\n"} @confLines;

my $url = 'git://github.com/teleshoes/tpbattstat-applet.git';
my $dir = 'tpbattstat-applet';
my $installCmd = './install.sh';

system "rm -rf /tmp/$dir";

system "git clone $url /tmp/$dir";

system "cd /tmp/$dir; $installCmd";

open FH, "> $confFile";
print FH @confLines;
close FH;
