#!/bin/bash

#Auto-hides mouse pointer, also makes it show up in xmonad
echo installing unclutter
sudo apt-get install unclutter
extra_opts="EXTRA_OPTS=\"-idle 0.6 -root -notclass Firefox\""
  
f=/etc/default/unclutter
tmp_f=/tmp/unclutter_default
echo "OLD: `cat $f | grep EXTRA_OPTS`"
echo "NEW: $extra_opts"
read -p "Replace options as above? (y/N)?"
if [ "$REPLY" == "y" ]; then
  cat $f | sed "s/EXTRA_OPTS.*/$extra_opts/" > $tmp_f
  sudo mv $tmp_f $f
  sudo chown root.root $f
  sudo chmod 644 $f
fi

