hostname = wolke-tab
mac = 4E:0E:B9:0D:E5:78

ipGuess = 192.168.11.59

vncDefaultArgs = --remote

defaultUser = android

sshArgs = -p 2222 -o LogLevel=ERROR -o NoHostAuthenticationForLocalhost=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null

ssidIp = wintermute        :: 192.168.11.59
ssidIp = FlipsAFad         :: 192.168.11.59
