hostname = wolke-tab
mac = E6:37:8D:48:48:3F

ipGuess = 192.168.11.61

vncDefaultArgs = --remote

defaultUser = android

sshArgs = -p 2222 -o LogLevel=ERROR -o NoHostAuthenticationForLocalhost=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null

ssidIp = wintermute        :: 192.168.11.61
ssidIp = FlipsAFad         :: 192.168.11.61
