#!/usr/bin/perl
use strict;
use warnings;

my $dev = '/proc/acpi/call';

if(not -e $dev){
  my $home = `echo -n \$HOME`;
  chdir "$home/acpi_call";
  system "make";
  system "insmod acpi_call.ko";
  if(not -e $dev){
    die "Could not find $dev; is module acpi_call loaded?\n";
  }
}

print "Calling : ";
my $call = join ' ', @ARGV;
open FH, "| tee /proc/acpi/call";
print FH "$call\n";
close FH;
print "Response: ";
system "cat /proc/acpi/call";
print "\n";
