#!/usr/bin/perl
use strict;
use warnings;

my $alarm = '/usr/share/alarm';

die "Usage:
  $0     - runs 'mplayer $alarm'
           reruns as the user running pulseaudio if run as root
";

my $pulseUser = `ps --no-heading -o user -C pulseaudio`;
$pulseUser =~ s/\n.*//s; #first line only

my $u = `whoami`;
chomp $u;

if($u eq 'root' and length($pulseUser) > 0 and $u ne $pulseUser){
  print "rerunning as pulse user $pulseUser\n";
  exec "su", $pulseUser, "-c", "$0 @ARGV";
}

system "term", "mplayer", $alarm;
