#!/usr/bin/perl
use strict;
use warnings;

if(@ARGV != 1 or $ARGV[0] !~ /^[a-zA-Z0-9][a-zA-Z0-9]$/){
  die "Usage: $0 fcronjob-name {two alphanumeric characters}\n";
}

my $job = shift;
system "alarm";

#MUST not output anything here, or fcronreset fails mysteriously
system "fcronjob $job off 1>/dev/null 2>/dev/null";
