#!/usr/bin/perl
use strict;
use warnings;

my $alarm = "$ENV{HOME}/Desktop/Music/alarm";

my $usage = "Usage:
  $0    runs mplayer $alarm
";

die $usage if @ARGV > 0;

system "DISPLAY=:0 term mplayer '$alarm'";
