#!/usr/bin/perl
use strict;
use warnings;

sub setLevel($);
sub writeTmpFile($);

my $fanDev = "/proc/acpi/ibm/fan";

my $usage = "Usage:
  $0
     print fan information
  $0 get
     print fan information
  $0 level
     set fan level
     level is 0-7, auto, disengaged, full-speed
     note that disengaged and full-speed are synonyms
";

sub main(@){
  my $level = shift;
  $level = 'get' if not defined $level;
  $level = 'disengaged' if $level eq 'full-speed';
  die $usage if @_ > 0 or $level !~ /^(get|[0-7]|auto|disengaged|full-speed)$/;

  my $info = `cat $fanDev`;

  if($level eq 'get'){
    print $info;
  }else{
    my $cur;
    if($info =~ /level:\s*(.*)\n/){
      $cur = $1;
    }
    if($cur eq $level){
      print "fan already set to $level\n";
    }else{
      print "$cur => $level\n";
      setLevel $level;
    }
  }
}

sub setLevel($){
  open FH, "> $fanDev" or die "Could not open $fanDev for writing\n$!\n";
  print FH "level $_[0]\n";
  close FH;
}

&main(@ARGV);
