#!/usr/bin/perl
use strict;
use warnings;

my $tab = "/etc/fcrontab";
my $spool = "/usr/local/var/spool/fcron";
my $alarmDest = "/usr/share/alarm";

if(`whoami` ne "root\n"){
  print "rerunning as root\n";
  exec "sudo", $0, @ARGV;
}

for my $line(`cat $tab`){
  if($line =~ /^\s*ALARM_PATH\s*=\s*(.*)/){
    my $file = $1;
    if(not -e $file){
      print STDERR "\n\nMISSING ALARM FILE: $file\n\n";
    }else{
      system "rm", "-f", $alarmDest;
      system "ln", "-s", $file, $alarmDest;
    }
  }
}

print "killing fcron and removing spooled tabs, twice\n";
system "killall -9 fcron; rm $spool/*";
system "killall -9 fcron; rm $spool/*";

print "removing fcrontab\n";
system "fcrontab -r";
print "loading fcrontab $tab\n";
system "fcrontab $tab";
