#!/usr/bin/perl
use strict;
use warnings;

my $tab = "/etc/fcrontab";
my $spool = "/usr/local/var/spool/fcron";

if(`whoami` ne "root\n"){
  print "rerunning as root\n";
  exec "sudo", $0, @ARGV;
}

print "killing fcron and removing spooled tabs, twice\n";
system "killall -9 fcron; rm $spool/*";
system "killall -9 fcron; rm $spool/*";

print "removing fcrontab";
system "fcrontab -r";
print "loading fcrontab $tab";
system "fcrontab $tab";
