#!/usr/bin/perl
use strict;
use warnings;

my $call = '/proc/acpi/call';

if(not -e $call){
  system "sudo build-acpi-call";
  if(not -e $call){
    die "$call does not exist- acpi_call module not loaded?\n";
  }
}

my @acpiOn = ['\\_SB.PCI0.PEG.VID._PS0'];
my @acpiOff = (
  [ "\\_SB.PCI0.PEG.VID._DSM"
  , "{0xF8,0xD8,0x86,0xA4,0xDA,0x0B,0x1B,0x47,0xA7,"
    ."0x2B,0x60,0x42,0xA6,0xB5,0xBE,0xE0}"
  , "0x100"
  , "0x1A"
  , "{0x1,0x0,0x0,0x3}"
  ],
  ["\\_SB.PCI0.PEG.VID._PS3"],
);


my $arg = shift;
$arg = '' if not defined $arg;

if($arg eq 'on'){
  for my $c(@acpiOn){
    system 'acpi-call', @$c;
  }
}elsif($arg eq 'off'){
  for my $c(@acpiOff){
    system 'acpi-call', @$c;
  }
}else{
  die "Usage: $0 [on|off]\n";
}

