#!/usr/bin/perl
#Copyright 2010 Elliot Wolk
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
use strict;
use warnings;

$ENV{PATH} = '/bin:/usr/bin';
my $home = $ENV{HOME};
$home =~ /^([a-zA-Z0-9_\-\/]+)$/;
my $configDir = "$1/resolvconf/";

my $opt = shift;
$opt = '' if not defined $opt;
$opt =~ /^([a-z]+)$/i;
$opt = defined $1 ? $1 : '';

my @availableConfigs;
my $config;
for my $file(`ls -1 $configDir`){
  if($file =~ /^resolv.conf.([a-z]+)\n?$/i){
    push @availableConfigs, $1;
    if($opt eq $1){
      $config = 1;
      last;
    }
  }
}

if ($opt eq '' or(
     $opt ne 'backup' and
     $opt ne 'restore' and
     $opt ne 'resolvconf' and
     not $config)){
  die "Usage $0 backup|restore|resolvconf|CONFIG
     {available configs=@availableConfigs}\n";
}


my $conf = '/etc/resolv.conf';
my $bak = '/etc/resolv.conf.bak';
my $real = '/etc/resolv.conf.real';
my $auto = '/etc/resolvconf/run/resolv.conf';

if($opt eq 'backup'){
  system "cp $real $bak";
}elsif($opt eq 'restore'){
  system "cp $bak $real";
}elsif($opt eq 'resolvconf'){
  system "rm $conf";
  system "ln -s $auto $conf";
}else{
  my $choice = $configDir . "resolv.conf.$opt";
  my $msg = "Applying $choice";
  if(-l $choice){
    my $link = `ls -l $choice`;
    if($link =~ /-> (.*)/){
      $msg .= " => $1";
    }
  }
  print "$msg\n";
  system "cp $choice $real";

  system "rm $conf";
  system "ln -s $real $conf";
}

