#!/usr/bin/perl
use strict;
use warnings;

sub run($){
  my $out = `$_[0]`;
  chomp $out;
  return $out;
}

my $year = run "date +'%Y'";
my $month = run "date +'%m'";
my $today = run "date +'%d'";

my $thisMonthDisplay = run "cal -h $month $year";

$today =~ s/^0/ /;
my $styledToday = "^bg(grey70)^fg(#111111)$today^fg()^bg()";
$thisMonthDisplay =~ s/(\s)$today(\s)/$1$styledToday$2/sx;


my $nextMonth = $month + 1;
my $nextMonthYear = $year;
if($nextMonth == 13){
  $nextMonth = 1;
  $nextMonthYear++;
}
my $nextMonthDisplay = run "cal -h $nextMonth $nextMonthYear";

my $prevMonth = $month - 1;
my $prevMonthYear = $year;
if($prevMonth == 0){
  $prevMonth = 12;
  $prevMonthYear--;
}
my $prevMonthDisplay = run "cal -h $prevMonth $prevMonthYear";

print "$prevMonthDisplay\n";
print "$thisMonthDisplay\n";
print "$nextMonthDisplay\n";
