#!/usr/bin/perl
use strict;
use warnings;

my $button = undef;
if(@ARGV == 3){
  $button = shift;
}
$button = '1' if not defined $button;

my $cmd = shift;
$cmd = '' if not defined $cmd;

my $markup = shift;
$markup = '' if not defined $markup;

print "^ca($button, $cmd)$markup^ca()\n";
