#!/usr/bin/perl
use strict;
use warnings;

my $PRINTERS = `echo -n \$HOME/.dzen2/printers`;

my $leftCmd = shift;
$leftCmd = '' if not defined $leftCmd;

my $rightCmd = shift;
$rightCmd = '' if not defined $rightCmd;

my $img = shift;
$img = '' if not defined $img;

my $markup = "^i($img)";
if($leftCmd ne ''){
  $markup = `$PRINTERS/click-action 1 '$leftCmd' '$markup'`;
  chomp $markup;
}
if($rightCmd ne ''){
  $markup = `$PRINTERS/click-action 3 '$rightCmd' '$markup'`;
  chomp $markup;
}

system "$PRINTERS/shift-up '$markup'";
