#!/usr/bin/perl
use strict;
use warnings;

my $PRINTERS = `echo -n \$HOME/.dzen2/printers`;

my ($leftCmd, $middleCmd, $rightCmd, $img);
($leftCmd, $img) = @ARGV if @ARGV == 2;
($leftCmd, $rightCmd, $img) = @ARGV if @ARGV == 3;
($leftCmd, $middleCmd, $rightCmd, $img) = @ARGV if @ARGV == 4;

die "Usage: $0 leftCmd [middleCmd] [rightCmd] image\n" if !$leftCmd or !$img;

my $markup = "^i($img)";
if($leftCmd){
  $leftCmd =~ s/'/'\\''/g;
  $markup = `$PRINTERS/click-action 1 '$leftCmd' '$markup'`;
  chomp $markup;
}
if($middleCmd ne ''){
  $middleCmd =~ s/'/'\\''/g;
  $markup = `$PRINTERS/click-action 2 '$middleCmd' '$markup'`;
  chomp $markup;
}
if($rightCmd ne ''){
  $rightCmd =~ s/'/'\\''/g;
  $markup = `$PRINTERS/click-action 3 '$rightCmd' '$markup'`;
  chomp $markup;
}

system "$PRINTERS/shift-up '$markup'";
