#!/usr/bin/perl
use strict;
use warnings;

my $LAUNCHERS = "\$HOME/.dzen2/launchers";
my $PRINTERS = "\$HOME/.dzen2/printers";

my $top = `date +'%a %b %d'`;
chomp $top;
my $bot = `date +'%H:%M:%S'`;
chomp $bot;

my $cmd = "$PRINTERS/calendar | $LAUNCHERS/popup 240 24 -fn inconsolata-14";

my $markup = `$PRINTERS/two-text-rows "$top" "$bot"`;
$markup = `$PRINTERS/click-action "$cmd" "$markup"`;
print $markup;

