#!/usr/bin/perl
use strict;
use warnings;

my $LAUNCHERS = "\$HOME/.dzen2/launchers";
my $PRINTERS = "\$HOME/.dzen2/printers";

sub raise($){
  my $text = shift;
  return "^p(;-8)$text^p(;8)";
}
sub lower($){
  my $text = shift;
  return "^p(;3)$text^p(;-3)";
}

sub addClickAction($$$){
  my $button = shift;
  my $cmd = shift;
  my $markup = shift;
  return "^ca($button, $cmd)$markup^ca()";
}

sub twoTextRows($$){
  my $top = shift;
  my $bot = shift;

  my $fst;
  my $snd;
  if(length $top > length $bot){
    $fst = lower($bot);
    $snd = raise($top);
  }else{
    $fst = raise($top);
    $snd = lower($bot);
  }

  return ''
   . '^ib(1)'
   . '^p(_LOCK_X)'
   . $fst
   . '^p(_UNLOCK_X)'
   . $snd
   . '^ib(0)'
   ;
}

my $top = `date +'%a %b %d'`;
chomp $top;
my $bot = `date +'%H:%M:%S'`;
chomp $bot;

my $calendarPopupCommand = "$PRINTERS/calendar | $LAUNCHERS/popup 240 24";
my $markup = twoTextRows $top, $bot;
$markup = addClickAction(1, $calendarPopupCommand, $markup);
print "$markup";

