#!/usr/bin/perl
use strict;
use warnings;

my $macRegex = qr/([a-f0-9]{2}:){5}[a-f0-9]{2}/i;

while(1){
  my $cnxn = `cnetworkmanager -c`;
  if($cnxn =~ /ACTIVATED \| (?:Auto )?(.*) \| $macRegex/i){
#    print "$1\n";
  }else{
#    print "<>\n";
  }
  print "\n";
  sleep 10;
}

