#!/usr/bin/perl
use strict;
use warnings;

my $LAUNCHERS = "\$HOME/.dzen2/launchers";
my $PRINTERS = "\$HOME/.dzen2/printers";

my $DEFAULT_ICON_DIR = `echo -n \$HOME/.dzen2/icons/36x36`;

my $usage = "Usage: $0 command [image_path]\n";
if(@ARGV != 1 and @ARGV != 2){
  die $usage;
}

my $cmd = shift;
my $img = shift;
$img = '' if not defined $img;

$cmd =~ s/\n*//gs;
$cmd =~ s/^\s*//g;
$cmd =~ s/\s*$//g;

$img =~ s/\n*//gs;
$img =~ s/^\s*//g;
$img =~ s/\s*$//g;

if($cmd eq ''){
  die $usage;
}

my $display;
if($img eq ''){
  $display = $cmd;
  $display =~ m@/([^/*])$@;
  my $maybeImg = "$DEFAULT_ICON_DIR/$display.xpm";
  if(-e $maybeImg){
    system "$PRINTERS/clickable-image \"$cmd\" '' \"$maybeImg\"";
  }else{
    system "$PRINTERS/click-action \"$cmd\" \"<$display>\"";
  }
}else{
  system "$PRINTERS/clickable-image \"$cmd\" '' \"$img\"";
}

