#!/usr/bin/perl
use strict;
use warnings;

my $DEFAULT_ICON_DIR = `echo -n \$HOME/.dzen2/icons/24x24`;

my $usage = "Usage: $0 command [image_path]\n";
if(@ARGV != 1 and @ARGV != 2){
  die $usage;
}

my $cmd = shift;
my $img = shift;
$img = '' if not defined $img;

$cmd =~ s/\n*//gs;
$cmd =~ s/^\s*//g;
$cmd =~ s/\s*$//g;

$img =~ s/\n*//gs;
$img =~ s/^\s*//g;
$img =~ s/\s*$//g;

if($cmd eq ''){
  die $usage;
}

my $display;
if($img eq ''){
  $display = $cmd;
  $display =~ m@/([^/*])$@;
  my $maybeImg = "$DEFAULT_ICON_DIR/$display.xpm";
  if(-e $maybeImg){
    $display = "^i($maybeImg)";
  }else{
    $display = "<$display>";
  }
}else{
  $display = "^i($img)";
}

print "^p(;-4)^ca(1,$cmd)$display^ca()^p(;4)";
