#!/usr/bin/perl
use strict;
use warnings;

my $delay = shift;
$delay = 1.5 if not defined $delay;

my $height = shift;
$height = 24 if not defined $height;

my $width = $height;

my $DIR = "\$HOME/.dzen2/printers";
my @colors = ("'#0072b2'", "'#0091e5'", "'#00a2fe'", "'#002f3d'", "'#000000'");

$, = ' ';
exec "$DIR/cpu-percentages $delay | $DIR/percent-monitor $width $height @colors";
