#!/usr/bin/perl
use strict;
use warnings;

my $LAUNCHERS = "\$HOME/.dzen2/launchers";
my $PRINTERS = "\$HOME/.dzen2/printers";

my $cpu = shift;
$cpu = '' if not defined $cpu;
my $delay = shift;
if($cpu !~ /^\d+$/){
  die "Usage: $0 cpu_index delay\n";
}
my $freq = "/sys/devices/system/cpu/cpu$cpu/cpufreq/scaling_cur_freq";
my $gov = "/sys/devices/system/cpu/cpu$cpu/cpufreq/scaling_governor";

local $| = 1;
while(1){
  my $currentGov = `cat $gov`;
  chomp $currentGov;
  $currentGov = substr $currentGov, 0, 2;

  my $currentFreq = `cat $freq`;
  chomp $currentFreq;
  $currentFreq = int($currentFreq * 10.0 / 1000.0 / 1000.0);
  if($currentFreq < 10){
    $currentFreq = "0$currentFreq";
  }

  my $msg = `$PRINTERS/two-text-rows "$currentFreq" "$currentGov"`;
  chomp $msg;
  print "$msg\n" or die "broken pipe";

  sleep $delay;
}

