#!/usr/bin/perl
use strict;
use warnings;
use Time::HiRes qw(sleep);

my $PRINTERS = "\$HOME/.dzen2/printers";

my $curGov = undef;
for my $dir(`find /sys/devices/system/cpu -regex '/sys/devices/system/cpu/cpu[0-9]*'`){
  chomp $dir;
  my $gov = "$dir/cpufreq/scaling_governor";
  my $currentGov = `cat $gov`;
  chomp $currentGov;
  if(defined $curGov and $curGov ne $currentGov){
    $curGov = '?';
    last;
  }
  $curGov = $currentGov;
}

if(not defined $curGov or length $curGov < 2){
  $curGov = '?';
}

if($curGov ne '?'){
  my $home = `echo -n \$HOME`;
  open FH, "< $home/.cpu_governor";
  my $lastGov = <FH>;
  chomp $lastGov;
  close FH;

  if($curGov ne $lastGov){
    system "sudo \$HOME/bin/cpu_governor all $curGov";
    $curGov = '!';
  }

}

my %bgs = qw(
  powersave    red
  performance  green
  ondemand     blue
  other        white
);

my $fg = 'black';
my $bg = $bgs{$curGov};
$bg = $bgs{other} if not defined $bg;

my $width = 2;

while(length $curGov < $width*2){
  if($curGov = ''){
    $curGov = '#' x $width*2;
  }
  $curGov = "$curGov$curGov";
}

my $top = substr $curGov, 0, $width;
my $bot = substr $curGov, $width, $width;
my $msg = `$PRINTERS/two-text-rows $top $bot 36`;
chomp $msg;
print "^bg($bg)^fg($fg)$msg^fg()^bg()";
