#!/usr/bin/perl
use strict;
use warnings;
use Time::HiRes qw(sleep);

my $PRINTERS = "\$HOME/.dzen2/printers";

my $curGov = undef;
for my $dir(`find /sys/devices/system/cpu -regex '/sys/devices/system/cpu/cpu[0-9]*'`){
  chomp $dir;
  my $gov = "$dir/cpufreq/scaling_governor";
  my $currentGov = `cat $gov`;
  chomp $currentGov;
  if(defined $curGov and $curGov ne $currentGov){
    $curGov = '??';
    last;
  }
  $curGov = $currentGov;
}

if(not defined $curGov or length $curGov < 2){
  $curGov = '??';
}

if($curGov ne '??'){
  my $home = `echo -n \$HOME`;
  open FH, "< $home/.cpu_governor";
  my $lastGov = <FH>;
  chomp $lastGov;
  close FH;

  if($curGov ne $lastGov){
    system "sudo \$HOME/bin/cpu_governor all $curGov";
    $curGov = '!!';
  }

}

my $top = substr $curGov, 0, 1;
my $bot = substr $curGov, 1, 1;
print "^p(2)";
system "$PRINTERS/two-text-rows $top $bot 36";
