#!/usr/bin/perl
use strict;
use warnings;

sub getCpuState($$){
  my $line = shift;
  my $state = shift;
  $line =~ /(\d*\.\d*)\%$state/;
  return $1;
}
open TOP, "top -bd .8 |";
local $| = 1;
while(my $line = <TOP>){
  if($line =~ /Cpu\(s\)/){
    my $user = getCpuState $line, 'us';
    my $system = getCpuState $line, 'sy';
    my $nice = getCpuState $line, 'ni';
    my $iowait = getCpuState $line, 'wa';
    my $idle = 100.0-$user-$system-$nice-$iowait;
    print "$user $system $nice $iowait $idle\n";
  }
}
