#!/usr/bin/perl
use strict;
use warnings;
use File::Basename;

my $dirname = dirname(__FILE__);
chdir $dirname;

my $module = shift;
$module =~ s/\.hs$//;
die "Usage: $0 <ghc-module-name> [ARGS]\n" if not defined $module;

exec "runghc", "-main-is", "$module.main", "$module.hs", @ARGV;
