#!/usr/bin/perl
use strict;
use warnings;

my $delay = shift;
$delay = 1.5 if not defined $delay;

my $height = shift;
$height = 24 if not defined $height;

my $width = $height;

my $DIR = "\$HOME/.dzen2/printers";
my @colors = ("'#00b25b'", "'#00e575'", "'#00fe81'", "'#a9f4c4'", "'#000000'");
$, = ' ';
exec "$DIR/mem-percentages $delay | $DIR/percent-monitor $width $height @colors";
