#!/usr/bin/perl
use strict;
use warnings;

sub percent($$){
  100.0 * $_[0] / $_[1];
}

while(1){
  my @lines = `free`;
  my ($total, $used, $free, $shared, $buffers, $cached);
  for my $line(@lines){
    if($line =~ /Mem:\s*(\d+)\s*(\d+)\s*(\d+)\s*(\d+)\s*(\d+)\s*(\d+)/){
      $total = $1;
      $used = $2;
      $free = $3;
      $shared = $4;
      $buffers = $5;
      $cached = $6;
      my $out = '';
      $out .= percent $used-$shared-$buffers-$cached, $total;
      $out .= ' ';
      $out .= percent $shared, $total;
      $out .= ' ';
      $out .= percent $buffers, $total;
      $out .= ' ';
      $out .= percent $cached, $total;
      $out .= ' ';
      $out .= percent $free, $total;
      print "$out\n";
      last;
    }
  }
  sleep 1;
}

