#!/usr/bin/perl
use strict;
use warnings;

my $LAUNCHERS = "\$HOME/.dzen2/launchers";
my $PRINTERS = "\$HOME/.dzen2/printers";

my $IMG_DIR = `echo \$HOME/.dzen2/icons/36x36`;

my $clickCmd = "pulse-mute microphone toggle";

my $mic = `pulse-mute microphone`;
my $img;
if($mic =~ /is muted/){
  $img = "$IMG_DIR/microphone-muted.xpm";
}elsif($mic =~ /is not muted/){
  $img .= "$IMG_DIR/microphone-unmuted.xpm";
}else{
  print "error\n";
  die 'Could not read microphone';
}

my $markup = `$PRINTERS/wrap-image "$img"`;
print `$PRINTERS/click-action "$clickCmd" "$markup"`;
