#!/usr/bin/perl
use strict;
use warnings;
my $IMG_DIR = `echo \$HOME/.dzen2/icons/24x24`;

my $str = '';
$str .= "^p(;-4)";
$str .= "^ca(1, pulse-mute microphone toggle)";
my $mic = `pulse-mute microphone`;
if($mic =~ /is muted/){
  $str .= "^i($IMG_DIR/microphone-muted.xpm)";
}elsif($mic =~ /is not muted/){
  $str .= "^i($IMG_DIR/microphone-unmuted.xpm)";
}else{
  $str .= "error";
}
$str .= "^ca()";
$str .= "^p(;4)";

print "$str\n";
