#!/usr/bin/perl
use strict;
use warnings;

my $LAUNCHERS = "\$HOME/.dzen2/launchers";
my $PRINTERS = "\$HOME/.dzen2/printers";

my $clickCmd = "sudo \$HOME/bin/sslvpn toggle";

my $color;
my $onoff;
if(`pidof openvpn`){
  $color = "green";
  $onoff = "yes";
}else{
  $color = "red";
  $onoff = "off";
}

my $markup = `$PRINTERS/two-text-rows "vpn" "$onoff"`;
$markup = "^fg($color)$markup^fg()";
$markup = `$PRINTERS/click-action "$clickCmd" "$markup"`;
print $markup;
