#!/bin/bash
if [ `pidof openvpn` ]; then
  color=green
  onoff=yes
else
  color=red
  onoff=off
fi
echo -n "^ca(1, sudo $HOME/bin/sslvpn toggle)"

echo -n "^p(_LOCK_X)"
echo -n "^p(;-8)"
echo -n "^fg($color)vpn^fg()"
echo -n "^p(;8)"
echo -n "^p(_UNLOCK_X)"

echo -n "^ib(1)"
echo -n "^p(;3)"
echo -n "^fg($color)$onoff^fg()"
echo -n "^p(;-3)"
echo -n "^ib(0)"

echo -n "^ca()"
