#!/usr/bin/perl
use strict;
use warnings;

my $PRINTERS = `echo -n \$HOME/.dzen2/printers`;
sub printer(@){
  my @args = @_;
  for my $arg(@args){
    $arg =~ s/\'/'\\''/g;
    $arg = "'$arg'";
  }
  my $out = `$PRINTERS/@args`;
  chomp $out;
  return $out;
}


my $profileDir = '~/.thunderbird/*.default';
my $exec = 'thunderbird'
my $processName = 'thunderbird-bin';
my $focusWinCmd = 'xdotool key --clearmodifiers alt+8';

my $runningLeftCmd = "xdotool key --clearmodifiers alt+8";
my $notRunningLeftCmd = "$exec";
my $leftCmd =
  "pidof $processName; " .
  "if [ \$? == 0 ]; " .
  "then $runningLeftCmd; " .
  "else $notRunningLeftCmd; " .
  "fi";


my $lClickCmd = "$leftCmd";
my $mClickCmd = "$exec -compose";
my $rClickCmd = "killall $processName";

my %ACCOUNTS = (
  'Gmail' => 'G',
  'LilleGroup' => 'L',
  'AOL - LiberiFataliVIII' => 'A');

sub isThunderbirdRunning();
sub background($);
sub green($);
sub red($);
sub getCounts();
sub pad2($);

sub main(){
  my $runningSymbol = '';

  if(isThunderbirdRunning()){
    $runningSymbol .= green ' ';
  }else{
    $runningSymbol .= red 'x';
  }

  my %counts = getCounts();
  my $len = 0;
  my $max = 0;
  my $total = 0;
  for my $count(values %counts){
    $len++;
    $max = $count if $count > $max;
    $total += $count;
  }

  my $top;
  my $bot;
  if($max > 99 or ($len > 2 && $total > 99)){
    $top = '99+';
    $bot = 'all';
  }elsif($len == 0){
    $top = '   ';
    $bot = '   ';
  }elsif($len == 1){
    my ($name1) = keys %counts;
    $top = (pad2 $counts{$name1}) . $name1;
    $bot = '   ';
  }elsif($len == 2){
    my ($name1, $name2) = sort keys %counts;
    $top = (pad2 $counts{$name1}) . $name1;
    $bot = (pad2 $counts{$name2}) . $name2;
  }else{
    $top = green ' ' . pad2 $total;
    $bot = 'all';
  }

  my $markup = printer 'two-text-rows', $top, $bot, 36;
  $markup = printer 'click-action', 1, $lClickCmd, $markup if $lClickCmd;
  $markup = printer 'click-action', 2, $mClickCmd, $markup if $mClickCmd;
  $markup = printer 'click-action', 3, $rClickCmd, $markup if $rClickCmd;
  $markup = green $markup;
  $markup = $runningSymbol . $markup;
  $markup = background $markup;
  print "$markup\n";
}

sub background($){
  return "^bg(black)$_[0]^bg()";
}
sub green($){
  return "^fg(green)$_[0]^fg()";
}
sub red($){
  return "^fg(red)$_[0]^fg()";
}

sub isThunderbirdRunning(){
  system "killall -0 $processName";
  return $? == 0;
}

sub getCounts(){
  my @accounts = `cat $profileDir/unread-counts 2>/dev/null`;
  my %counts;
  for my $acc(@accounts){
    if($acc =~ /^([0-9]+):(.*)\n?$/){
      my $count = $1;
      my $name = $2;
      my $display = $ACCOUNTS{$name};
      if($count > 0 && defined $display){
        $counts{$display} = $count;
      }
    }
  }
  return %counts;
}

sub pad2($){
  return ' ' x (2 - (length $_[0])) . $_[0];
}

main;
