#!/usr/bin/perl
use strict;
use warnings;

my $top = shift;
$top = '' if not defined $top;
my $bot = shift;
$bot = '' if not defined $bot;

sub raise($){
  my $text = shift;
  return "^p(;-8)$text^p(;8)";
}
sub lower($){
  my $text = shift;
  return "^p(;3)$text^p(;-3)";
}
sub stripMarkup($){
  my $markup = shift;
  $markup =~ s/\^\^/A/gsxi;
  $markup =~ s/\^[a-z]+\([^)]*\)//gsxi;
  return $markup;
}

my $fst;
my $snd;

if(length stripMarkup $top > length stripMarkup $bot){
  $fst = lower($bot);
  $snd = raise($top);
}else{
  $fst = raise($top);
  $snd = lower($bot);
}

print ''
  . '^ib(1)'
  . '^p(_LOCK_X)'
  . $fst
  . '^p(_UNLOCK_X)'
  . $snd
  . '^ib(0)'
  . "\n"
  ;

