#!/bin/bash
sudo add-apt-repository ppa:videolan/stable-daily
sudo add-apt-repository ppa:pidgin-developers/ppa
sudo add-apt-repository ppa:chromium-daily/stable
sudo add-apt-repository ppa:mozillateam/thunderbird-stable
sudo add-apt-repository ppa:sparkers/ppa
sudo add-apt-repository ppa:ubuntu-wine/ppa
  
#mesa/opengl/xorg nouveau/ati/intel bleeding edge
sudo add-apt-repository ppa:oibaf/graphics-drivers

