#!/bin/bash
sudo add-apt-repository ppa:sparkers/ppa
sudo add-apt-repository ppa:ubuntu-wine/ppa
  
#mesa/opengl/xorg nouveau/ati/intel bleeding edge
sudo add-apt-repository ppa:oibaf/graphics-drivers

