#!/bin/bash
echo; echo;
read -p "Add third party repos (y/N)?"
if [ "$REPLY" == "y" ]; then
  #NetworkManager and nm-applet
  sudo add-apt-repository ppa:network-manager/trunk
  
  #pidgin stable releases
  sudo add-apt-repository ppa:pidgin-developers/ppa

  #wine unstable developer releases
  sudo add-apt-repository ppa:ubuntu-wine/ppa

  #chrome stable daily releases
  sudo add-apt-repository ppa:chromium-daily/stable

  #thunderbird stable
  sudo add-apt-repository ppa:mozillateam/thunderbird-stable

  echo Add the below for Mesa, OpenGL, xorg drivers nouveau/ati/intel
  read -p "add bleeding edge open source gfx drivers ppa (y/N)?"
  if [ "$REPLY" == "y" ]; then
    #mesa bleeding edge
    sudo add-apt-repository ppa:oibaf/graphics-drivers
  fi

  read -p "Add gimp unstable from matthaeus (y/N)?"
  if [ "$REPLY" == "y" ]; then
    #gimp unstable
    sudo add-apt-repository ppa:matthaeus123/mrw-gimp-svn
  fi

  read -p "ADD KERNEL PPA (y/N)?"
  if [ "$REPLY" == "y" ]; then
    #kernel bleeding edge
    sudo add-apt-repository ppa:kernel-ppa/ppa
  fi

  echo; echo;
  read -p "software-properties-gtk to toggle partner/multiverse/universe? (y/N)"
  if [ "$REPLY" == "y" ]; then
    gksu software-properties-gtk
  fi;
fi

