#!/usr/bin/perl
use strict;
use warnings;

my $tty = '6';
my $profileFile = "$ENV{HOME}/.profile";

my $user = $ENV{SUDO_USER};
if(not defined $user){
  $user = $ENV{USER};
}
if($user eq "root" or length $user == 0){
  die "USER or SUDO_USER var must be set and not root"
    . " {e.g.: SUDO_USER=john $0}\n";
}

sub run(@);
sub replaceLine($$$);
sub setupInit();
sub setupProfile();

sub main(@){
  die "Usage: $0\n" if @_ > 0;

  setupInit();
  setupProfile();
  my @displayManagers = qw(lxdm gdm kdm lightdm);
  for my $displayManager(@displayManagers){
    run "sudo apt-get remove --purge $displayManager";
  }
}

sub run(@){
  print "@_\n";
  system @_;
}

sub replaceLine($$$){
  my ($file, $destLine, $matchWord) = @_;
  my @lines = `cat $file`;

  my $found = 0;
  for my $line(@lines){
    $line = '' if $line =~ /^#$destLine/;
    next if $line =~ /^\s*#/;
    if(not $found and $line =~ /\Q$matchWord\E/){
      $found = 1;
      if($line eq $destLine){
        print "$file unchanged\n";
      }else{
        print "$file:\n  $line=>\n  $destLine";
        $line = "#$line" . $destLine;
      }
    }
  }
  if(not $found){
    print "appending $destLine";
    push @lines, $destLine;
  }
  open FH, "| sudo tee $file >/dev/null" or die "Couldnt write to $file\n";
  print FH @lines;
  close FH;
}

sub setupInit(){
  my $cmd = "/bin/login -f $user tty$tty </dev/tty$tty >/dev/tty$tty 2>&1";

  print "===========================\n";
  print "SETTING UP INIT\n";
  my $tab = "/etc/inittab";
  if(-e $tab){
    replaceLine $tab, "$tty:2345:respawn:$cmd\n", "tty$tty";
  }else{
    print "!!!!!ERROR: $tab doesnt exist\n";
  }
  print "===========================\n";
}

sub setupProfile(){
  my $autoLoginSection = ''
    . "##AUTOLOGIN START##\n"
    . "if [ -z \"\$DISPLAY\" ]; then\n"
    . "  if [ \"\$(tty)\" == \"/dev/tty$tty\" ]; then\n"
    . "    exec startx\n"
    . "  fi\n"
    . "fi\n"
    . "##AUTOLOGIN END##\n"
    ;
  
  my $profile = `cat $profileFile`;
  $profile =~ s/##AUTOLOGIN START##.*##AUTOLOGIN END##\n?//s;
  $profile .= $autoLoginSection;

  print "Replacing autologin section in $profileFile with:\n";
  print "-----\n$autoLoginSection-----\n";

  open FH, "> $profileFile";
  print FH $profile;
  close FH;
}

&main(@ARGV);
