#!/usr/bin/perl
use strict;
use warnings;

if(`whoami` ne "root\n"){
  print "rerunning as root\n";
  exec "sudo", $0, @ARGV;
}

my $dir = '/etc/bash_completion.d';

my $files = {
  'sudo-aliases' => "complete -F _root_command suod sudp\n",
  'spawn' => "complete -F _root_command spawn spawnex spawnexsudo\n",
  'mnt' => '_mntnames(){
              local cur names
              cur="${COMP_WORDS[COMP_CWORD]}"

              if [ ${#COMP_WORDS[@]} == 3 ]; then
                names=`mnt -n`
                COMPREPLY=( $(compgen -W "$names" -- $cur) )
              elif [ ${#COMP_WORDS[@]} == 2 ]; then
                COMPREPLY=( $(compgen -W "-m -u -g -n -l" -- $cur) )
              else
                COMPREPLY=()
              fi
            }

            complete -F _mntnames mnt
           ',
};

for my $file(keys %$files){
  my $content = $$files{$file};
  open FH, "> $dir/$file" or die "Couldnt open file $dir/$file\n";
  print FH $content;
  close FH;
}
