#!/bin/bash
echo; echo;
read -p "Configure keyboard (y/N)?"
if [ "$REPLY" == "y" ]; then
  TAB=`echo -en "\t"`
  KBD_OPTIONS="[terminate${TAB}terminate:ctrl_alt_bksp,caps${TAB}caps:escape]"
  echo keyboard options: "$KBD_OPTIONS"
  echo "note: caps:escape makes CapsLock additional Escape key"
  echo "      terminate:ctrl_alt_bksp makes Ctrl+Alt+Backspace kill xsession"
  read -p "Add the above keyboard options (y/N)?"
  if [ "$REPLY" == "y" ]; then
    gconftool --set \
      /desktop/gnome/peripherals/keyboard/kbd/options \
      --type list --list-type string "$KBD_OPTIONS"
  fi
  echo; echo;
  read -p "Run keybindings (y/N)?"
  if [ "$REPLY" == "y" ]; then
    keybindings
  fi;
fi;

