#!/bin/bash
echo; echo;
echo Desktop background
read -p "set desktop bg = birth of venus? (y/N)?"
if [ "$REPLY" == "y" ]; then
  gconftool-2 --type string --set /desktop/gnome/background/picture_filename "/home/wolke/Desktop/Backgrounds/venere.jpg"
fi

echo; echo;
read -p "set desktop custom folder icons and remove places in ~/? (y/N)"
if [ "$REPLY" == "y" ]; then
  rmdir ~/Music ~/Documents ~/Downloads ~/Pictures ~/Templates ~/Videos
  set-desktop-folder-icons
fi

