#!/bin/bash
echo; echo;
bt_disable_cmd="echo disable > /proc/acpi/ibm/bluetooth"
read -p "append '$bt_disable_cmd' to /etc/init.d/rc.local (y/N)?"
if [ "$REPLY" == "y" ]; then
  cmd="\n#turn off bluetooth\n$bt_disable_cmd"
  sudo bash -c "echo -e '$cmd' >> /etc/init.d/rc.local"
fi

