#!/usr/bin/perl
use strict;
use warnings;

sub sudoRerun();
sub readConf($);
sub writeConf($);
sub mergeConf($$);
sub replaceConf($$);

my $file = '/etc/environment';

my %vars = (
);

sub main(@){
  sudoRerun();
  replaceConf $file, \%vars;
}

sub sudoRerun(){
  if(`whoami` ne "root\n"){
    print "rerunning as root\n";
    exec "sudo", $0, @ARGV;
  }
}

sub readConf($){
  my $s = shift();
  my $conf = {};
  for my $line(split /[\n\r]+/, $s){
    if($line =~ /^(.*)=(.*)$/){
      $$conf{$1} = $2;
    }
  }
  return $conf;
}

sub writeConf($){
  my %conf = %{shift()};
  my $s = '';
  for my $key(sort keys %conf){
    $s .= "$key=$conf{$key}\n";
  }
  return $s;
}

sub mergeConf($$){
  my %orig = %{shift()};
  my %changes = %{shift()};
  for my $key(keys %changes){
    $orig{$key} = $changes{$key};
  }
  return \%orig;
}

sub replaceConf($$){
  my $file = shift;
  my $changes = shift;
  my $conf = readConf `cat $file`;
  my $content = writeConf(mergeConf($conf, $changes));
  open FH, "> $file" or die "Couldnt open $file for writing.\n";
  print FH $content;
  close FH;
}

&main(@ARGV);
