#!/bin/bash
echo; echo;
read -p "Add perl-5.10 symlink for escribe (y/N)?"
if [ "$REPLY" == "y" ]; then
  sudo ln -s perl /usr/bin/perl-5.10
fi

echo; echo;
read -p "add escribe.com servers to /etc/hosts (y/N)?"
if [ "$REPLY" == "y" ]; then
  sudo /home/wolke/bin/escribe-hosts
fi

