#!/bin/bash
echo; echo;
read -p "disable STUPID forced compiz plugins (y/N)?"
if [ "$REPLY" == "y" ]; then
  echo; echo;
  echo Disabling forced compiz plugins
  mkdir -p ~/.config/compiz
  echo "COMPIZ_PLUGINS=\"\"" > ~/.config/compiz/compiz-manager
fi

echo; echo;
read -p "replace compiz wallpaper plugin with a patched one that works (y/N)?"
if [ "$REPLY" == "y" ]; then
  TAR=`echo ~/Desktop/Software/wallpaper-compiz-workaround.tar.bz2`
  echo "Downloaded from http://www.mediafire.com/?usji79x5yiu5d3z"
  echo "workaround from http://forum.ubuntu-fr.org/viewtopic.php?id=421649"
  if [ -e $TAR ]; then
    echo "using: $TAR"
    mkdir /tmp/wallpaper
    cd /tmp/wallpaper
    tar -xf $TAR
    cd /usr/lib/compiz
    SEX=`date +%s`
    sudo mv libwallpaper.a libwallpaper.a_$SEX
    sudo mv libwallpaper.la libwallpaper.la_$SEX
    sudo mv libwallpaper.so libwallpaper.so_$SEX
    sudo cp /tmp/wallpaper/usr/lib/compiz/libwallpaper* .
    rm -rf /tmp/wallpaper
  else
    echo "fetch the file above and put it at: $TAR"
  fi
fi

echo; echo;
echo wish i could do: ccsm  preferences  import ~/compiz.profile
read -p "run ccsm so you can do it? (y/N)"
if [ "$REPLY" == "y" ]; then
  ccsm
fi

