#!/bin/bash

read -p "run all the really good gconf settings (y/N)?"
if [ "$REPLY" == "y" ]; then

echo;
echo Turning off screensaver idle activation
gconftool-2 --set /apps/gnome-screensaver/idle_activation_enabled --type Boolean "False"
gconftool-2 --set /apps/gnome-screensaver/lock_enabled --type Boolean "False"

echo;
echo Default to the text location bar in nautilus, instead of bread crumb buttons
gconftool-2 --set /apps/nautilus/preferences/always_use_location_entry --type Boolean "True"

echo;
echo Setting buttons to :minimize,maximize,close {all on the right}
gconftool-2 --set /apps/metacity/general/button_layout --type String ":minimize,maximize,close"

echo;
echo "Terminal bg/fg -> black/green, menubar off"
gconftool-2 --set /apps/gnome-terminal/profiles/Default/use_theme_colors --type boolean  false
gconftool-2 --set /apps/gnome-terminal/profiles/Default/background_color --type string "#000000000000"
gconftool-2 --set /apps/gnome-terminal/profiles/Default/foreground_color --type string "#0000FFFF0000"
gconftool-2 --set /apps/gnome-terminal/profiles/Default/default_show_menubar --type boolean "False"
gconftool-2 --set /apps/gnome-terminal/profiles/Default/font --type string "Inconsolata Medium 12"
gconftool-2 --set /apps/gnome-terminal/profiles/Default/use_system_font --type boolean false

echo;
echo Setting monospace font to inconsolata
gconftool-2 --set /desktop/gnome/interface/monospace_font_name --type string "Inconsolata Medium 12"

echo; echo;
echo tapclick off, dont disable touchpad while typing, dont mouse scroll
gconftool-2 --set /desktop/gnome/peripherals/touchpad/tap_to_click --type Boolean "False"
gconftool-2 --set /desktop/gnome/peripherals/touchpad/disable_while_typing --type Boolean "False"
gconftool-2 --set /desktop/gnome/peripherals/touchpad/scroll_method --type Integer "0"
gconftool-2 --set /desktop/gnome/peripherals/touchpad/horiz_scroll_enabled --type Boolean "False"


echo; echo;
echo power mgr: do nothing on crit battery, blank screen on lid close, etc.
gconftool-2 --set /apps/gnome-power-manager/notify/discharging --type Boolean "False"
gconftool-2 --set /apps/gnome-power-manager/actions/critical_battery --type String "nothing"
gconftool-2 --set /apps/gnome-power-manager/actions/critical_ups --type String "nothing"
gconftool-2 --set /apps/gnome-power-manager/actions/low_ups --type String "nothing"
gconftool-2 --set /apps/gnome-power-manager/actions/sleep_type_battery --type String "nothing"
gconftool-2 --set /apps/gnome-power-manager/actions/sleep_type_ac --type String "nothing"
gconftool-2 --set /apps/gnome-power-manager/backlight/battery_reduce --type Boolean "False"
gconftool-2 --set /apps/gnome-power-manager/backlight/enable --type Boolean "False"
gconftool-2 --set /apps/gnome-power-manager/timeout/sleep_computer_ac --type Integer "0"
gconftool-2 --set /apps/gnome-power-manager/timeout/sleep_computer_battery --type Integer "0"
gconftool-2 --set /apps/gnome-power-manager/timeout/sleep_computer_ups --type Integer "0"
gconftool-2 --set /apps/gnome-power-manager/timeout/sleep_display_ac --type Integer "1800"
gconftool-2 --set /apps/gnome-power-manager/timeout/sleep_display_battery --type Integer "600"
gconftool-2 --set /apps/gnome-power-manager/timeout/sleep_display_ups --type Integer "1800"
gconftool-2 --set /apps/gnome-power-manager/buttons/lid_ac --type String "blank"
gconftool-2 --set /apps/gnome-power-manager/buttons/lid_battery --type String "blank"
gconftool-2 --set /apps/gnome-power-manager/disks/spindown_enable_battery --type Boolean "False"
gconftool-2 --set /apps/gnome-power-manager/disks/spindown_enable_ac --type Boolean "False"
gconftool-2 --set /apps/gnome-power-manager/ui/icon_policy --type String "always"

fi
