#!/usr/bin/perl
use strict;
use warnings;

my @cmdLineOpts = qw(
  quiet
  splash
  pcie_aspm=force
  i915.i915_enable_rc6=1
);
my $cmdLine = '"' . (join ' ', @cmdLineOpts) . '"';

my $file = '/etc/default/grub';
my %configs = (
 GRUB_TIMEOUT => 3,
 GRUB_HIDDEN_TIMEOUT => undef,
 GRUB_HIDDEN_TIMEOUT_QUIET => undef,
 GRUB_CMDLINE_LINUX_DEFAULT => $cmdLine,
);

print "change $file ->\n";
for my $key(sort keys %configs){
  if(defined $configs{$key}){
    print " $key => $configs{$key}\n";
  }else{
    print " comment out: $key\n";
  }
}
print "(y/N)?";
my $reply = <STDIN>;
if(lc $reply ne "y\n"){
  print "skipped\n";
  exit 0;
}


open IN, "< $file" or die "Could not open $file for reading: $!";
my @lines = <IN>;
close IN;

for my $line(@lines){
  for my $configKey(keys %configs){
    if($line =~ /^$configKey\s*=/){
      if(not defined $configs{$configKey}){
        $line = "#$line";
        delete $configs{$configKey};
      }else{
        $line = "$configKey=$configs{$configKey}\n";
        delete $configs{$configKey};
      }
    }
  }
}

for my $configKey(keys %configs){
  if(defined $configs{$configKey}){
    push @lines, "$configKey=$configs{$configKey}\n";
  }
}


open OUT, "| sudo tee $file";
print OUT @lines;
close OUT;

system "sudo update-grub";
