#!/bin/bash
echo; echo;
echo 'change /etc/default/grub ->'
echo ' GRUB_HIDDEN_TIMEOUT=3'
echo ' GRUB_HIDDEN_TIMEOUT_QUIET=false'
echo and then run 'update-grub'
read -p "Modify grub (y/N)?"
if [ "$REPLY" == "y" ]; then
  sudo ~/bin/config_grub
  sudo update-grub
fi

