#!/bin/bash
echo; echo;
echo "e.g.: wolke-t400, wolke-t60, wolke-blue, wolke-n900, wolk-desktop"
read -p "hostname='$HOSTNAME' Type a new hostname (y/N)?"
if [ "$REPLY" == "y" ]; then
  OLD=$HOSTNAME
  read -p "type hostname:"
  NEW=$REPLY
  echo $NEW | sudo tee /etc/hostname
  cat /etc/hosts | sed s/$OLD/$NEW/g | sudo tee /etc/hosts
fi
