#!/bin/bash
echo; echo;
read -p "apt-get update and install free software? (y/N)?"
if [ "$REPLY" == "y" ]; then
  echo; echo;
  echo Updating packages info...
  sudo apt-get update

  echo; echo;
  echo Installing free software packages...
  sudo apt-get install -y vim-gnome
  sudo apt-get install -y openvpn
  sudo apt-get install -y ssh curl gparted pidgin thunderbird \
    ghc cabal-install ant subversion alltray xmacro mplayer vlc python-pygame \
    nautilus-gksu hwinfo chromium-browser wine1.2 htop \
    xsel flac libsvn-java xtightvncviewer x11vnc gvfs-bin git \
    gnome-common ttf-inconsolata gimp ffmpeg wmctrl xsane php5 \
    libxslt1-dev libgdbm-dev rhythmbox link-monitor-applet gnome-do \
    librsvg2-bin fbreader xdotool powertop kernel-package openjdk-6-source \
    gnome-color-chooser unclutter lltag meld python-mutagen libaudio-wma-perl \
    dir2ogg macchanger wvdial normalize-audio
  sudo apt-get install -y alarm-clock-applet
  sudo apt-get install -y aptitude
fi

echo; echo;
read -p "install unclutter: Auto-hide pointer (fixes ptr in xmonad)? (y/N)?"
if [ "$REPLY" == "y" ]; then
  sudo apt-get install unclutter
fi

echo; echo;
read -p "Install i7z? (y/N)?"
if [ "$REPLY" == "y" ]; then
  echo Installing libncurses5-dev and latest i7z from svn
  install-i7z
fi

echo; echo;
read -p "Install mike's runghc? (y/N)?"
if [ "$REPLY" == "y" ]; then
  git clone git://github.com/bacchanalia/runghc.git /tmp/runghc
  cd /tmp/runghc
  cabal install
  rm -rf /tmp/runghc
fi

echo; echo;
read -p "Install pidgin pipe-notification plugin? (y/N)?"
if [ "$REPLY" == "y" ]; then
  install-pidgin-pipe-notification
fi

echo; echo;
read -p "install xmonad and dzen2? (y/N)"
if [ "$REPLY" == "y" ]; then
  sudo apt-get install xmonad libghc6-xmonad-contrib-dev

  $HOME/bin/install-dzen2

  #move the %-named files in .xmonad to its place
  for file in `ls $HOME/.xmonad/%*`; do
    loc=`echo $file | sed 's/[^%]*%/%/' | sed 's/%/\//g'`
    echo copying $file to $loc
    sudo cp $file $loc
  done
fi;

echo; echo;
read -p "install silkscreen font (y/N)?"
if [ "$REPLY" == "y" ]; then
  SS_DIR=/usr/share/fonts/truetype/ttf-silkscreen
  sudo mkdir -p $SS_DIR
  cd $SS_DIR
  sudo wget http://www.kottke.org/plus/type/silkscreen/download/silkscreen.zip
  sudo unzip silkscreen.zip
  sudo rm silkscreen.zip
  sudo fc-cache -fv
fi

echo; echo;
read -p "Install compa (displays command output for gnome-panel) (y/N)?"
if [ "$REPLY" == "y" ]; then
  sudo apt-get install libpanel-applet2-dev build-essential
  cd
  cp ~/Desktop/Software/compa-*.tar.gz .
  if [ $? ]; then
    wget 'http://compa.googlecode.com/files/compa-0.98.tar.gz'
  fi
  tar -xf compa-*.tar.gz
  rm compa-*.tar.gz
  cd compa-*
  ./configure --prefix=/usr
  make
  sudo make install
  cd ..
  rm -rf compa-*
  killall gnome-panel
fi;

echo; echo;
read -p "install tp-smapi {thinkpad battery module} (y/N)?"
if [ "$REPLY" == "y" ]; then
  sudo apt-get install -y tp-smapi-dkms
  sudo ~/bin/tp-smapi-install

  echo; echo;
  read -p "install tpbattstat-applet (y/N)?"
  if [ "$REPLY" == "y" ]; then
    ~/bin/build-tpbattstat-applet
  fi
fi

echo; echo;
read -p "Build cvoicecontrol at ~/apps/cvoicecontrol-0.9alpha/ (y/N)?"
if [ "$REPLY" == "y" ]; then
  cd ~/apps/cvoicecontrol-0.9alpha/
  configure
  make
  sudo make install
  cd
fi


