#!/bin/bash
echo; echo;
read -p "Auto-hide mouse pointer (also makes it show up in xmonad)? (y/N)?"
if [ "$REPLY" == "y" ]; then
  echo installing unclutter
  sudo apt-get install unclutter
  extra_opts="EXTRA_OPTS=\"-idle 0.6 -root -notclass Firefox\""
  
  f=/etc/default/unclutter
  tmp_f=/tmp/unclutter_default
  echo "OLD: `cat $f | grep EXTRA_OPTS`"
  echo "NEW: $extra_opts"
  read -p "Replace options as above? (y/N)?"
  if [ "$REPLY" == "y" ]; then
    cat $f | sed "s/EXTRA_OPTS.*/$extra_opts/" > $tmp_f
    sudo mv $tmp_f $f
    sudo chown root.root $f
    sudo chmod 644 $f
  fi
fi

echo; echo;
read -p "Install i7z? (y/N)?"
if [ "$REPLY" == "y" ]; then
  echo Installing libncurses5-dev and latest i7z from svn
  install-i7z
fi

echo; echo;
read -p "Install pidgin pipe-notification plugin? (y/N)?"
if [ "$REPLY" == "y" ]; then
  install-pidgin-pipe-notification
fi

echo; echo;
read -p "install xmonad and dzen2? (y/N)"
if [ "$REPLY" == "y" ]; then
  sudo apt-get install xmonad libghc6-xmonad-contrib-dev

  $HOME/bin/install-dzen2

  #move the %-named files in .xmonad to its place
  for file in `ls $HOME/.xmonad/%*`; do
    loc=`echo $file | sed 's/[^%]*%/%/' | sed 's/%/\//g'`
    echo copying $file to $loc
    sudo cp $file $loc
  done
fi;

