#!/usr/bin/perl
use strict;
use warnings;

print "installing ghc and haskell-platform from the repos\n";
system "sudo apt-get install ghc haskell-platform";
print "\n\n\n";

my @cabalPackages = qw(
  runghc
  xmonad xmonad-contrib
  regex-pcre-builtin unixutils utf8-string monad-loops

  cmdargs pureMD5 transformers tagged semigroups data-default dlist entropy
  cereal X11 syb binary largeword posix-timer split
);

my @xmonadDeps = qw(
  cdbs dctrl-tools fdupes html-xml-utils intltool libexpat1-dev libffi-dev
  libfontconfig1-dev libfreetype6-dev libxft-dev libxinerama-dev libxrender-dev
  python-scour x11proto-render-dev x11proto-xinerama-dev xutils-dev
);

print "Install cabal packages {xmonad} (y/N)? ";
if(lc <STDIN> eq "y\n"){
  print "xmonad deps: @xmonadDeps\n";
  system "sudo apt-get install @xmonadDeps";
  
  #cp the %-named files in .xmonad to its place
  for my $file (`ls \$HOME/.xmonad/%*`){
    chomp $file;
    my $loc = $file;
    $loc =~ s/^[^%]*%/%/;
    $loc =~ s/%/\//g;
    system "sudo cp $file $loc";
  }

  system "cabal update";
  system "cabal install @cabalPackages";
}
