#!/bin/bash
echo; echo;
read -p "Incude non-free software (y/N)?"
if [ "$REPLY" == "y" ]; then
  sudo apt-get update

  echo
  echo installing ubuntu-restricted-extras
  sudo apt-get install ubuntu-restricted-extras
  
  echo
  echo installing skype
  sudo apt-get install skype

  echo
  echo Installing non-free encrypted dvd reader
  sudo /usr/share/doc/libdvdread4/install-css.sh
  
  echo; echo;
  read -p "fix 32-bit flash {export GDK_NATIVE_WINDOWS} (y/N)?"
  if [ "$REPLY" == "y" ]; then
    sudo ~/bin/config_flash
  fi

fi

