#!/usr/bin/perl
use strict;
use warnings;

for my $file(`ls installs/`){
  chomp $file;
  print "$file\n";
  print "run installs/$file [y/N]? ";
  if(<STDIN> =~ /^[yY]\n$/){
    system "installs/$file";
  }
  print "\n\n";
}
