#!/bin/bash
echo; echo;
read -p "Auto-hide mouse pointer (also makes it show up in xmonad)? (y/N)?"
if [ "$REPLY" == "y" ]; then
  echo installing unclutter
  sudo apt-get install unclutter
fi

echo; echo;
read -p "Install i7z? (y/N)?"
if [ "$REPLY" == "y" ]; then
  echo Installing libncurses5-dev and latest i7z from svn
  install-i7z
fi

echo; echo;
read -p "Install mike's runghc? (y/N)?"
if [ "$REPLY" == "y" ]; then
  git clone git://github.com/bacchanalia/runghc.git /tmp/runghc
  cd /tmp/runghc
  cabal install
  rm -rf /tmp/runghc
fi

echo; echo;
read -p "Install pidgin pipe-notification plugin? (y/N)?"
if [ "$REPLY" == "y" ]; then
  install-pidgin-pipe-notification
fi

echo; echo;
read -p "install xmonad and dzen2? (y/N)"
if [ "$REPLY" == "y" ]; then
  sudo apt-get install xmonad libghc6-xmonad-contrib-dev

  $HOME/bin/install-dzen2

  #move the %-named files in .xmonad to its place
  for file in `ls $HOME/.xmonad/%*`; do
    loc=`echo $file | sed 's/[^%]*%/%/' | sed 's/%/\//g'`
    echo copying $file to $loc
    sudo cp $file $loc
  done
fi;

