#!/usr/bin/perl
use strict;
use warnings;

my @ghcPackages = qw(ghc haskell-platform);
my @xmonadPackages = qw(xmonad libghc6-xmonad-contrib-dev);
my @cabalPackages = qw(
  runghc
  regex-pcre-builtin unixutils utf8-string monad-loops

  hlint
  cmdargs pureMD5 transformers tagged semigroups data-default dlist entropy
  cereal X11 syb binary largeword posix-timer split
);

system "sudo", "apt-get", "install", @ghcPackages;
system "sudo", "apt-get", "install", @xmonadPackages;

system "cabal", "update";
system "cabal", "install", @cabalPackages";
