#!/usr/bin/perl
use strict;
use warnings;

my @ghcDebs = qw(ghc haskell-platform);
my @xmonadDebs = qw(xmonad libghc6-xmonad-contrib-dev);
my @cabalDebs = qw(gtk2hs-buildtools);
my @cabalPackages = qw(
  runghc taffybar
  regex-pcre-builtin unixutils utf8-string monad-loops
  cmdargs pureMD5 transformers tagged semigroups data-default dlist entropy
  cereal X11 syb binary largeword posix-timer split hlint
);

if(@ARGV == 1 and $ARGV[0] eq '--clean'){
  system "sudo", "apt-get", "purge", @ghcDebs, @xmonadDebs;
  system "sudo", "rm", "-rf", "/usr/lib/ghc", "/usr/lib/haskell-packages";
  system "rm", "-rf", "$ENV{HOME}/.ghc/", "$ENV{HOME}/.cabal/"
}elsif(@ARGV != 0){
  die "Usage: $0  or  $0 --clean";
}

system "sudo", "apt-get", "install", @ghcDebs;
system "sudo", "apt-get", "install", @xmonadDebs;

system "sudo", "apt-get", "install", @cabalDebs;

system "cabal", "update";
system "cabal", "install", @cabalPackages;
