#!/bin/bash
echo; echo;
read -p "Incude non-free software (y/N)?"
if [ "$REPLY" == "y" ]; then
  echo
  echo installing ubuntu-restricted-extras
  sudo apt-get install ubuntu-restricted-extras
  
  echo
  echo Installing non-free encrypted dvd reader
  sudo /usr/share/doc/libdvdread4/install-css.sh
  
fi

