#!/usr/bin/perl
use strict;
use warnings;

system "sudo", "apt-get", "purge", "notification-daemon";
system "sudo", "apt-get", "purge", "notify-osd";
system "sudo", "apt-get", "install", "xfce4-notifyd";
