#!/usr/bin/perl
use strict;
use warnings;

system "sudo", "apt-get", "purge", "notification-daemon";
system "sudo", "apt-get", "purge", "notify-osd";
system "sudo", "apt-get", "install", "xfce4-notifyd";

#chdir "/tmp";
#system "wget", "http://ftp.us.debian.org/debian/pool/main/p/pidgin-libnotify/pidgin-libnotify_0.14-9_amd64.deb";
#system "sudo dpkg -i /tmp/pidgin-libnotify*.deb";
#system "sudo", "apt-get", "-f", "install";
system "sudo", "apt-get", "install", "pidgin-libnotify";
