#!/bin/bash
echo; echo;
echo /opt and /var/opt are usually empty
echo this script wont remove them if theyre not, it will back them up
read -p "replace /opt and /var/opt with links to ~/conf? (y/N)?"
if [ "$REPLY" == "y" ]; then
  set -x
  sudo rm /opt
  sudo rmdir /opt
  sudo mv -f /opt /opt_bak_`date +%s`
  mkdir -p ~/conf/opt
  sudo ln -s ~/conf/opt /opt

  sudo rm /var/opt
  sudo rmdir /var/opt
  sudo mv -f /var/opt /var/var_opt_bak_`date +%s`
  mkdir -p ~/conf/var-opt
  sudo ln -s ~/conf/var-opt /var/opt
fi

