#!/bin/bash
echo; echo;
echo setting up /opt and /var/opt to point to ~/conf
read -p "replace /opt and /var/opt with links ~/conf? (y/N)?"
if [ "$REPLY" == "y" ]; then
  sudo rm /opt
  sudo rmdir /opt
  sudo mv -f /opt /opt_bak_`date +%s`
  mkdir -p ~/conf/opt
  sudo ln -s ~/conf/opt /opt

  sudo rm /var/opt
  sudo rmdir /var/opt
  sudo mv -f /var/opt /var/var_opt_bak_`date +%s`
  mkdir -p ~/conf/var-opt
  sudo ln -s ~/conf/var-opt /var/opt
fi

