#!/usr/bin/perl
use strict;
use warnings;

my %pkgs = (
  '1now' => [qw(
    ssh rsync openvpn git vim-gtk firefox
  )],
  '2desktop' => [qw(
    ttf-inconsolata
    gnome-human-icon-theme
  )],
  '3apps' => [qw(
    pidgin finch thunderbird chromium-browser
    gimp xsane parted gparted meld
    libreoffice fbreader evince calibre
    gimp-resynthesizer file-roller
  )],
  '4media' => [qw(
    mplayer vlc
    fluidsynth vmpk
  )],
  '5tools' => [qw(
    acpi
    mesa-utils
    gnome-disk-utility
    unetbootin
    bluez bluetooth
    macchanger curl
    inotify-tools
    wvdial
    ntp
    p7zip
    daemon
    xtightvncviewer x11vnc libnotify-bin
    xinput
    htop powertop lshw hwinfo testdisk
    normalize-audio eterm
    feh qiv gqview gthumb jhead
    xbacklight xmacro xsel xcalib xdotool wmctrl scrot
  )],
  '6programming' => [qw(
    sqlite3
    subversion
    mercurial
    ant
    git-gui
    php5
    wine
    aptitude
    openjdk-7-source
    eclipse
  )],
  '7deps' => [qw(
    module-assistant
    python-pygame
    cmake
    gvfs-bin
    libxslt1-dev
    libgdbm-dev
    librsvg2-bin
    kernel-package
    libavcodec-extra-53
  )],
  '8audioLibs' => [qw(
    flac ffmpeg pulseaudio pavucontrol
    lltag libaudio-wma-perl python-mutagen atomicparsley
    cdparanoia exfalso
    cuetools shntool
  )],
);



for my $pkgGroup(sort keys %pkgs){
  print "\n\n\n\n\n$pkgGroup:\n";
  my @packages = @{$pkgs{$pkgGroup}};
  system "sudo apt-get install -y @packages";
}
