#!/usr/bin/perl
use strict;
use warnings;

my %pkgs = (
  '1now' => [qw(
    ssh openvpn git vim-gtk firefox
  )],
  '2desktop' => [qw(
    ttf-inconsolata
  )],
  '3apps' => [qw(
    pidgin thunderbird chromium-browser
    gimp xsane gparted meld
    libreoffice fbreader evince calibre
    gimp-resynthesizer
  )],
  '4media' => [qw(
    mplayer vlc
    fluidsynth vmpk
  )],
  '5tools' => [qw(
    gnome-disk-utility
    unetbootin
    bluez
    macchanger curl
    inotify-tools
    wvdial
    ntp
    gconf-editor
    p7zip
    daemon
    xtightvncviewer x11vnc libnotify-bin
    htop powertop hwinfo testdisk
    normalize-audio eterm
    qiv gqview gthumb
    xbacklight xmacro xsel xcalib xdotool wmctrl scrot
  )],
  '6programming' => [qw(
    sqlite3
    subversion
    mercurial
    ant
    git-gui
    php5
    wine
    aptitude
    openjdk-7-source
  )],
  '7deps' => [qw(
    ppa-purge
    module-assistant
    python-pygame
    cmake
    gvfs-bin
    libxslt1-dev
    libgdbm-dev
    librsvg2-bin
    kernel-package
  )],
  '8audioLibs' => [qw(
    flac ffmpeg pulseaudio
    lltag libaudio-wma-perl python-mutagen atomicparsley
  )],
);



for my $pkgGroup(sort keys %pkgs){
  print "\n\n\n\n\n$pkgGroup:\n";
  my @packages = @{$pkgs{$pkgGroup}};
  system "sudo apt-get install -y @packages";
}
