#!/usr/bin/perl
use strict;
use warnings;

my @packages = qw(
  unrar
);

die "No packages\n" if @packages == 0;

my $sourcesFile = "/etc/apt/sources.list.d/nonfree.list";
my $target = 'wheezy';
my $tree = 'non-free';
my $mirror = 'http://ftp.us.debian.org/debian/';

sub run(@){
  print "@_\n";
  system @_;
}

run "echo \"deb $mirror $target $tree\" | sudo tee \"$sourcesFile\"";
run "sudo", "apt-get", "update";
run "sudo", "apt-get", "-t", $target, "install", @packages;
run "sudo", "rm", $sourcesFile;
run "sudo", "apt-get", "update";
