#!/usr/bin/perl
use strict;
use warnings;

my @packages = qw(
  iceweasel icedove
);

my $sourcesFile = "/etc/apt/sources.list.d/unstable.list";
my $target = 'experimental';
my $tree = 'main';
my $mirror = 'http://ftp.us.debian.org/debian/';

sub run(@){
  print "@_\n";
  system @_;
}

run "echo \"deb $mirror $target $tree\" | sudo tee \"$sourcesFile\"";
run "sudo", "apt-get", "update";
run "sudo", "apt-get", "-t", $target, "install", @packages;
run "sudo", "rm", $sourcesFile;
run "sudo", "apt-get", "update";
