#!/usr/bin/perl
use strict;
use warnings;

my %pkgs = (
  now => [qw(
    ssh openvpn git vim firefox
  )],
  design => [qw(
    ttf-inconsolata
  )],
  apps => [qw(
    pidgin thunderbird chromium-browser
    vim-gtk
    gimp xsane
    gparted meld
    synapse
    libreoffice fbreader evince calibre
  )],
  media => [qw(
    mplayer vlc
  )],
  tools => [qw(
    bluez
    macchanger curl
    inotify-tools
    wvdial
    ntp
    gconf-editor
    p7zip
    xtightvncviewer x11vnc libnotify-bin
    htop powertop hwinfo testdisk
    normalize-audio qiv eterm
    xbacklight xmacro xsel xcalib xdotool wmctrl scrot
  )],
  programming => [qw(
    ant
    subversion libsvn-java
    php5
    wine
    aptitude
    openjdk-6-source
  )],
  deps => [qw(
    python-pygame
    cmake
    gvfs-bin
    libxslt1-dev
    libgdbm-dev
    librsvg2-bin
    kernel-package
  )],
  audioLibs => [qw(
    flac ffmpeg pulseaudio
    lltag libaudio-wma-perl python-mutagen atomicparsley
  )],
);



for my $pkgGroup(keys %pkgs){
  my @packages = @{$pkgs{$pkgGroup}};
  system "sudo apt-get install @packages";
}

print "REMOVING ALL HOTKEYS ~/.config/hotkeys\n";
system "rm -r ~/.config/hotkeys";
