#!/bin/bash
echo; echo;
echo Install some perl modules:
echo Date::Calc   File::Slurp   B::Bytecode   XML::LibXSLT
echo Term::ReadKey   Term::Size::Perl   Date::Manip
echo Lingua::JA::Romanize::Japanese
read -p "install the above perl modules(more prompts for each)? (y/N)?"
if [ "$REPLY" == "y" ]; then
  echo we need libssl-dev to install the perl packages below
  sudo apt-get install libssl-dev

  PERL_MM_USE_DEFAULT=1

  echo upgrading CPAN module
  sudo cpan CPAN

  echo setting up Config.pm to make install faster and more autonomous
  CPAN=/etc/perl/CPAN/Config.pm
  if [ -e $CPAN ]; then
    #install prerequisites without prompting
    sudo /home/wolke/bin/cpan-oconf $CPAN prerequisites_policy follow
    #limit build cache to 1000mb
    sudo /home/wolke/bin/cpan-oconf $CPAN build_cache 1000
    #reuse the build_dir in later sessions (successful makes not repeated)
    sudo /home/wolke/bin/cpan-oconf $CPAN build_dir_reuse yes
    #if a module wants to temp install a lib, permanently install it
    sudo /home/wolke/bin/cpan-oconf $CPAN build_requires_install_policy yes
    #submit test reports if possible
    sudo /home/wolke/bin/cpan-oconf $CPAN test_report yes
    #if theres a record of a successful test for this machine, skip test
    sudo /home/wolke/bin/cpan-oconf $CPAN trust_test_report_history yes
  fi

  read -p "install Test::Reporter and upgrade all modules in cpan? (y/N)"
  if [ "$REPLY" == "y" ]; then
    sudo cpan Test::Reporter
    sudo perl -MCPAN -e upgrade
  fi

  sudo cpan Term::ReadKey
  sudo cpan Date::Manip
  sudo cpan Date::Calc
  sudo cpan File::Slurp
  sudo cpan Term::Size::Perl
  sudo cpan Lingua::JA::Romanize::Japanese

  echo
  read -p "cpan -f -i B::Bytecode? (y/N)"
  if [ "$REPLY" == "y" ]; then
    sudo cpan -f -i B::Bytecode
  fi

  echo
  read -p "install XML::LibXSLT? (y/N)"
  if [ "$REPLY" == "y" ]; then
    sudo cpan XML::LibXSLT
  fi
fi

