#!/usr/bin/perl
use strict;
use warnings;

my %repoModules = (
  'Date::Calc'       => 'libdate-calc-perl',
  'File::Slurp'      => 'libfile-slurp-perl',
  'XML::LibXSLT'     => 'libxml-libxslt-perl',
  'Term::ReadKey'    => 'libterm-readkey-perl',
  'Term::Size::Perl' => 'libterm-size-perl',
  'Date::Manip'      => 'libdate-manip-perl',
  'Test::Reporter'   => 'libtest-reporter-perl',
);

my @cpanModules = qw(
  B::ByteCode
  Lingua::JA::Romanize::Japanese
);

my %oconf = (
  prerequisites_policy => 'follow',       #always install prereqs
  build_cache => '1000',                  #limit build cache to 1000mb
  build_dir_reuse => 'yes',               #successful makes not repeated
  build_requires_install_policy => 'yes', #permanently install 'temp' libs
  test_report => 'yes',                   #submit test reports if possible
  trust_test_report_history => 'yes',     #skip tests reported for this machine
);

sub oconfSet($$$);

sub main(@){
  for my $mod(keys %repoModules){
    print "installing $mod from repo\n";
    system "sudo", "apt-get", "install", $repoModules{$mod};
  }

  print "\n\n";

  my $cpanConfig = '/etc/perl/CPAN/Config.pm';
  if(-e $cpanConfig){
    for my $key(%oconf){
      oconfSet($cpanConfig, $key, $oconf{$key});
    }
  }
  system "PERL_MM_USE_DEFAULT=1 sudo cpan CPAN";
  system "PERL_MM_USE_DEFAULT=1 sudo perl -MCPAN -e upgrade";
  for my $mod(@cpanModules){
    print "installing $mod from cpan\n";
    system "PERL_MM_USE_DEFAULT=1 sudo cpan $mod";
  }
}

sub oconfSet($$$){
  my $file = shift;
  my $config = shift;
  my $value = shift;

  open FH, "< $file" or die "could not read $file\n";
  my @lines = <FH>;
  close FH;

  $value =~ s/\[/\\[/;
  $value =~ s/\]/\\]/;
  $value = "q[$value]";

  for my $line(@lines){
    if($line =~ / ( \s* '$config' \s* => \s* )  (.*)  ( , \s* ) $/x){
      print "old: $line";
      $line = "$1$value$3";
      print "new: $line";
      print "\n";
      last;
    }
  }

  open FH, "> $file" or die "could not write $file\n";
  print FH @lines;
  close FH;
}

&main(@ARGV);
