#!/usr/bin/perl
use strict;
use warnings;

my $dir = '/lib/plymouth/themes';
my $initramfsFunctions = '/usr/share/initramfs-tools/scripts/functions';

my $curTheme = 'kells';

sub drawImageText($$$);
sub diff($$);
sub initramfsLogging();

sub run(@){
  print "@_\n";
  system @_;
}

sub main(@){
  die "Usage: $0\n" if @_ > 0;

  die "No image text\n" if not -e "plymouth/image-text";
  my $text = `cat plymouth/image-text`;
  chomp $text;
  print "Image text: $text\n";

  for my $theme(`cd plymouth; ls -dA *`){
    chomp $theme;
    next if not -d "plymouth/$theme";
    my $baseImage = "plymouth/$theme/${theme}_base.png";
    my $textImage = "plymouth/$theme/${theme}.png";
    drawImageText $text, $baseImage, $textImage;
    run "sudo", "rm", "-rf", "$dir/$theme/";
    run "sudo", "cp", "-ar", "plymouth/$theme", $dir;
    run "rm", $textImage;
  }

  run "sudo", "rm", "$dir/default.plymouth";
  run "sudo", "ln", "-s",
    "$curTheme/$curTheme.plymouth", "$dir/default.plymouth";
  initramfsLogging();
}

sub drawImageText($$$){
  my ($text, $src, $dest) = @_;
  die "No base image $src\n" if not -e $src;
  run "convert",
    "-pointsize", "60",
    "-fill", "black",
    "-draw", "text 1450,60 '$text'",
    $src, $dest;
}

sub diff($$){
  my ($old, $new) = ('/tmp/old', '/tmp/new');
  open FH, "> /tmp/old";
  print FH $_[0];
  close FH;
  open FH, "> /tmp/new";
  print FH $_[1];
  close FH;
  print "---diff---\n";
  system "diff $old $new";
  print "----------\n\n";
  system "rm $old $new";
}

sub initramfsLogging(){
  my $logFunction = ''
    . "_log_msg()\n"
    . "{\n"
    . "\t####PLYMOUTH START#####\n"
    . "\tif [ -x /bin/plymouth ]; then\n"
    . "\t\t/bin/plymouth update --status=\"\$\@\"\n"
    . "\tfi\n"
    . "\t####PLYMOUTH END#####\n"
    . "\tif [ \"\$quiet\" = \"y\" ]; then return; fi\n"
    . "\tprintf \"\$\@\"\n"
    . "}\n"
    . "\n"
    ;

  my $f = `cat $initramfsFunctions`;
  my $oldF = $f;
  $f =~ s/_log_msg\(\)\s*{[^}]*}\n*/$logFunction/s;
  
  print "\n\nreplacing _log_msg() in $initramfsFunctions\n";
  diff $oldF, $f;

  open FH, "| sudo tee $initramfsFunctions > /dev/null"
    or die "Couldnt write to $initramfsFunctions\n";
  print FH $f;
  close FH;
}

&main(@ARGV);
