#!/bin/bash
echo; echo;
read -p "Remove compiz.* and unity.* (y/N)?"
if [ "$REPLY" == "y" ]; then
  sudo apt-get remove compiz.* unity.*
fi;

echo; echo;
echo remove indicator-me, indicator-session, and indicator-messages
read -p "remove everything in indicator-applet except volume (y/N)?"
if [ "$REPLY" == "y" ]; then
  sudo apt-get remove indicator-messages indicator-me indicator-session
fi

echo; echo;
read -p "remove overlay scrollbar (y/N)?"
if [ "$REPLY" == "y" ]; then
  FILE="/etc/X11/Xsession.d/80overlayscrollbars"
  ARG="export LIBOVERLAY_SCROLLBAR=0"
  sudo bash -c "echo $ARG > $FILE"

  sudo apt-get remove .*overlay-scrollbar.*
fi

echo; echo;
read -p "autoremove? (y/N)?"
if [ "$REPLY" == "y" ]; then
  sudo apt-get autoremove
fi

