#!/bin/bash
echo; echo;
read -p "remove NETWORK MANAGER!! get innernets odervise (y/N)?"
if [ "$REPLY" == "y" ]; then
  sudo apt-get remove network-manager.*
fi

echo; echo;
read -p "autoremove? (y/N)?"
if [ "$REPLY" == "y" ]; then
  sudo apt-get autoremove
fi

