#!/usr/bin/perl
use strict;
use warnings;


my $dir = "$ENV{HOME}/Desktop/Software/scratchbox";
my $script = "harmattan-sdk-setup_modified.py";
my @rootstraps = qw(
  arm-public-sdk-rootstrap.tgz
  i386-public-sdk-rootstrap.tgz
);

for my $f((@rootstraps, $script)){
  if(not -e "$dir/$f"){
    die "Missing file: $dir/$f\n";
  }
}

print "REMEMBER TO DO:
/scratchbox/login
sb-menu
  {SELECT}
  {ARMEL}
";
system "sudo python $dir/$script admininstall";


