#!/bin/bash

STUFF_LINE="UUID=97a5f9ed-6519-48c6-a12c-32e6d7864baf /media/stuff ext4 defaults 0 2"
TMPFS_LINE="tmpfs /tmp tmpfs defaults,noatime,nodev,nosuid,mode=1777 0 0"
for line in "$STUFF_LINE" "$TMPFS_LINE"; do  
  echo; echo;
  echo $line
  read -p "Add the above line to /etc/fstab for secondary hard disk (y/N)?"
  if [ "$REPLY" == "y" ]; then
    echo $line | sudo tee -a /etc/fstab
  fi
done

