#!/bin/bash
test -x initctl && sudo initctl start cups
test -x /etc/init.d/cups && sudo /etc/init.d/cups start
sudo rm -rf /etc/cups/printers.conf
sudo rm -rf /etc/cups/ppd/*
sudo cp $HOME/printers/printers.conf /etc/cups/printers.conf
sudo cp $HOME/printers/ppd/* /etc/cups/ppd/
sudo chown root.lp /etc/cups/printers.conf
sudo chown root.root /etc/cups/ppd/*
test -x initctl && sudo initctl stop cups
test -x /etc/init.d/cups && sudo /etc/init.d/cups start
