#!/usr/bin/perl
use strict;
use warnings;

if(`whoami` ne "root\n"){
  print "rerunning as root\n";
  exec "sudo", $0, @ARGV;
}

system "apt-get install transmission-daemon";

my %settings = (
  "download-dir"                => "\"$ENV{HOME}/Desktop/Torrents\"",
  "rpc-authentication-required" => 'false',
  "rpc-enabled"                 => 'true',
  "rpc-whitelist-enabled"       => 'false',
);

my @files = (
  "/etc/transmission-daemon/settings.json",
  "$ENV{HOME}/.config/transmission-daemon/settings.json",
);

for my $file(@files){
  print "$file\n";
  open FH, "< $file" or die "Couldnt read $file\n";
  my @lines = <FH>;
  for my $line(@lines){
    for my $key(keys %settings){
      if($line =~ /^(\s*)"$key"\s*:\s*(.*?)(,?)\s*$/){
        my $indent = $1;
        my $oldVal = $2;
        my $comma = $3;
        my $val = $settings{$key};
        if($oldVal ne $val){
          print "$key:\n  $oldVal => $val$comma\n";
        }
        $line = "$indent\"$key\": $val$comma\n";
      }
    }
  }
  close FH;
  open FH, "> $file" or die "Couldnt write $file\n";
  print FH @lines;
  close FH;
}

system "/etc/init.d/transmission-daemon reload";
system "/etc/init.d/transmission-daemon restart";
