#!/bin/bash
echo; echo;
read -p "sync /var/cache/apt with ~/apt-cache (y/N)?"
if [ "$REPLY" == "y" ]; then
  A="/var/cache/apt"
  B="$HOME/apt-cache"
  sudo rsync -av $A/ $B
  sudo rsync -av $B/ $A
  sudo chown -R $USER.$USER $B
  sudo chown -R root.root $A
fi

