#!/usr/bin/perl
use strict;
use warnings;

my @lines = ('ACTION=="remove", GOTO="keyboard_end"',
             'SUBSYSTEM!="input", GOTO="keyboard_end"',
             'KERNEL!="event*", GOTO="keyboard_end"',
             'ENV{DMI_VENDOR}=="LENOVO*", ' .
               'KERNELS=="input*", ' .
               'ATTRS{name}=="ThinkPad Extra Buttons", ' .
               'RUN+="keymap $name 0x13 search 0x1A prog2"',
             'LABEL="keyboard_end"');
my $out = (join "\n", @lines) . "\n";

my $file = '/etc/udev/rules.d/w520.rules';

print "$out\nwrite above to $file? (y/N) ";
if(lc <STDIN> eq "y\n"){
  open FH, "| sudo tee $file" or die "Could not open $file for writing\n";
  print FH $out;
  close FH;
}
