#!/bin/bash
echo; echo;
read -p "Upgrade packages? (y/N)?"
if [ "$REPLY" == "y" ]; then
  echo Upgrading packages
  sudo apt-get upgrade
fi


echo; echo;
read -p "Upgrade packages with aptitude {includes new installs and heldback} (y/N)?"
if [ "$REPLY" == "y" ]; then
  sudo aptitude upgrade
fi

