#!/usr/bin/perl
use strict;
use warnings;

system "sudo apt-get install "
  . ' libc6 libfontconfig1 libgcc1 libgdk-pixbuf2.0-0 libglib2.0-0'
  . ' libperl5.14 libx11-6 libxft2 libxrender1 base-passwd ncurses-term'
;
system "sudo apt-get install rxvt-unicode-256color";

my $configFile = "$ENV{HOME}/.Xdefaults";
my $perlDir = '/usr/lib/urxvt/perl';
my $utilPerlDir = 'urxvt/perl';

my %config = (
  "foreground"        => "green",
  "background"        => "black",
  "transparent"       => "true",
  "shading"           => "20",
  "font"              => "xft:Inconsolata:pixelsize=16",

  "scrollBar"         => "false",
  "scrollTtyKeypress" => "true",
  "scrollTtyOutput"   => "false",
  "scrollWithBuffer"  => "true",

  "perl-lib"          => "$perlDir", 
  "perl-ext-common"   => "clipboard",

  "iso14755"          => "false",
  "keysym.C-S-C"      => "perl:clipboard:copy",
  "keysym.C-S-V"      => "perl:clipboard:paste",

  "keysym.A-F7"       => "perl:clipboard:copy",
  "keysym.A-F8"       => "perl:clipboard:paste",
);

my $urxvtConf = join '', map {"URxvt.$_: $config{$_}\n"} sort keys %config;
$urxvtConf .= "# section gets overwritten by $0\n";
$urxvtConf = "###URXVT_START###\n$urxvtConf###URXVT_END###\n";
print $urxvtConf;

system "touch $configFile";
my $conf = `cat $configFile`;
$conf =~ s/###URXVT_START###\n.*###URXVT_END###\n//si;
$conf .= $urxvtConf;
open FH, "> $configFile" or die "Couldnt open $configFile for writing\n";
print FH $conf;
close FH;


for my $file(`ls $utilPerlDir`){
  chomp $file;
  my $cmd = "sudo cp $utilPerlDir/$file $perlDir";
  print "$cmd\n";
  system $cmd;
}
