#!/usr/bin/perl
use strict;
use warnings;

my $card = "6000g2a";
my $version = "18.168.6.1";

my $dir = "iwlwifi-$card-ucode-$version";
my $tar = "$dir.tgz";
my $url = "http://intellinuxwireless.org/iwlwifi/downloads/$tar";

sub run(@){
  print "@_\n";
  system @_;
}

chdir "/tmp";
run "rm -r iwlwifi*";
run "wget", $url;
run "tar", "-xf", $tar;
chdir $dir;
my $ucode = `ls iwlwifi-$card-*.ucode`;
chomp $ucode;

run "sudo rm /lib/firmware/iwlwifi-$card-*.ucode";
run "sudo", "cp", $ucode, "/lib/firmware";

run "sudo", "modprobe", "-r", "iwlwifi";
run "sudo", "modprobe", "iwlwifi";
