#!/bin/bash
echo; echo;
read -p "install compat-wireless backports for iwlagn 300mbps 802.11n (y/N)?"
if [ "$REPLY" == "y" ]; then
  sudo apt-get install linux-backports-modules-compat-wireless-2.6.36-maverick-generic
fi

echo; echo;
echo intel 5300 has n disabled by default
echo options iwlagn 11n_disable=1
echo turning fucking 802.11N on
read -p "enable wireless-N? (y/N)"
if [ "$REPLY" == "y" ]; then
  sudo /home/wolke/bin/wifiN on
fi

