#!/usr/bin/perl
use strict;
use warnings;
use Term::ReadKey;

print "Ensure wolke-home-config git repo, and make symlinks into ~? (y/N) ";
if(lc <STDIN> eq "y\n"){
  my $home = `echo -n \$HOME`;
  my $dir = "$home/wolke-home-config";

  chdir $dir;
  my @symlinks = `ls -A -1`;
  my %includes = (
    ".git" => 0,
  );

  if(not -d $dir){
    system "git clone git\@github.com:teleshoes/wolke-home-config.git $dir";
  }

  for my $sym(@symlinks){
    chomp $sym;
    if(not defined $includes{$sym} or $includes{$sym}){
      system 'ln', '-s', "$dir/$sym", "$home";
    }
  }
}
