#!/usr/bin/perl
use strict;
use warnings;
use Term::ReadKey;

print "Ensure wolke-home-config git repo, and make symlinks into ~? (y/N) ";
if(lc <STDIN> eq "y\n"){
  my $home = `echo -n \$HOME`;
  my $dir = "$home/wolke-home-config";

  my @symlinks = qw(
    .alarm .bashrc bin .dzen2 .gitconfig .gtk-bookmarks
    .htoprc install.pl .profile resolvconf .twip utils
    .vimrc .xmonad);

  if(not -d $dir){
    system "git clone git\@github.com:teleshoes/wolke-home-config.git $dir";
  }

  for my $sym(@symlinks){
    system 'ln', '-s', "$dir/$sym", "$home";
  }
}
