#!/usr/bin/perl
use strict;
use warnings;

my $repo = 'git@github.com:teleshoes/wolke-home-config.git';
my %config = (
  'core.repositoryformatversion', '0',
  'core.filemode', 'true',
  'core.bare', 'false',
  'core.logallrefupdates', 'true',
  'remote.origin.url', 'git@github.com:teleshoes/wolke-home-config.git',
  'remote.origin.fetch', '+refs/heads/*:refs/remotes/origin/*',
  'branch.master.remote', 'origin',
  'branch.master.merge', 'refs/heads/master',
);


if(not -e "$ENV{HOME}/.git"){
  chdir '/tmp';
  system "rm -rf homeconfig";

  system "git clone $repo homeconfig";
  chdir "homeconfig";
  system "git pull origin master";
  system "mv .git $ENV{HOME}/";

  for my $key(sort keys %config){
    my $val = $config{$key};
    system "git", "config",
      "--file", "$ENV{HOME}/.git/config",
      $key, $val;
  }
}
