#!/usr/bin/perl
use strict;
use warnings;

my $usage = "
  $0 [OPTS] [CMD [ARG ARG ... ]]
  
  Provids a consistent cli to several terminal emulators.
  Spawns the terminal and disowns it {this is bash-specific}

  OPTS
    -t|--title|-T|-title TITLE   sets the title on terminals that support it
";

sub main(@){
  my $title = '';
  if(@_ > 1 and $_[0] =~ /^(-title|-T|--title|-t)$/){
    shift;
    my $t = shift;
    $t =~ s/'/'\\''/g;
    $title = "-title '$t'";
  }

  my @cmd = @_;
  s/'/'\\''/g foreach @cmd;
  $_ = "'$_'" foreach @cmd;
  
  if(@cmd == 1 and $cmd[0] =~ / /){
    @cmd = ("-e", "bash", "-c", @cmd);
  }elsif(@cmd > 0){
    @cmd = ("-e", @cmd);
  }

  exec "bash", "-c", "urxvt $title @cmd & disown";
}

&main(@ARGV);
