#!/usr/bin/perl
use strict;
use warnings;

my $LINE_HEIGHT = 24;

my $width = shift;
$width = '' if not defined $width;
my $lines = shift;
$lines = '' if not defined $lines;
if($width !~ /^-?\d+$/ or $lines !~ /^\d+$/){
  die "Usage: $0 width_max_px lines [additional dzen2 arguments]\n" .
    "width_max_px and lines control whether popup is " .
    "to the left/right or above/below the cursor.\n" .
    "i simply count a line as $LINE_HEIGHT px\n";
}

my $mouse = `xdotool getmouselocation`;
$mouse =~ /x:(\d+) y:(\d+)/;
my ($x, $y, $screen) = ($1, $2, $3);

if($x > $width){
  $x -= $width;
}
my $height = $lines*$LINE_HEIGHT;
if($y > $height){
  $y -= $height;
}

exec "dzen2 -x $x -y $y -w $width -l $lines @ARGV";
