#!/bin/bash
LAUNCHERS="$HOME/.dzen2/launchers"

WIDTH=$1
LINES=$2
shift
shift

$LAUNCHERS/current-mouse $WIDTH $LINES $@ -p -sa -c \
 -e \''onstart=uncollapse;button1=exit;button2=exit;button3=exit'\'
