#!/bin/sh
case "${1}" in
    resume|thaw)
        u="$USER"
        if [ "$u" = "root" ] && [ -n "$SUDO_USER" ]; then
            u="$SUDO_USER"
        fi
        if [ -f "/home/$u/.xconfig" ]; then
            /bin/sh "/home/$u/.xconfig"
        fi
;;
esac
